yj2222/freemarket_sample_53d

app/views/products/index.html.haml
=> [WIP]Update index.html.haml

app/controllers/products_controller.rb
=> [WIP]edit_products_controller

Gemfile, Gemfile.lock
#WHAT
gem 'sqlite3'をバージョン指定し、
gem 'sqlite3', '~> 1.4.1'に記述を変更しました。
#WHY
本番環境にGemを導入する際に発生するエラーを回避するためです
=> [WIP]Gemファイルの変更

config/database.yml, config/unicorn.rb
#WHAT
データベースを作成する前に設定を記述しました。
#WHY
データベースを作成しないと本番環境でのアプリの起動ができないためです
=> [WIP]database.yamlの編集

config/unicorn.rb
#WHAT
unicorn.rbに記述を追加しました
#WHY
Nginxを介した処理を行うためです
=> [WIP]ユニコーンファイルの編集

Capfile, config/deploy.rb, config/deploy/production.rb, config/deploy/staging.rb, config/unicorn.rb
#WHAT
自動デプロイの設定を、production.rb、deploy.rbに記載し、unicorn.rbファイルを編集しました
#WHY
自動デプロイ機能を実装するため
=> [WIP]自動デプロイの設定

app/assets/javascripts/mypages.coffee, app/assets/javascripts/products.coffee, app/assets/stylesheets/application.css.scss, app/assets/stylesheets/mypages/_mypage-edit.scss, app/controllers/mypages_controller.rb, app/views/mypages/_edit.html.haml, app/views/mypages/_profile.html.haml, app/views/mypages/index.html.haml, config/application.rb
=> マイページ編集ページのマークダウン

app/assets/stylesheets/_details.scss, app/assets/stylesheets/_reset.scss, app/assets/stylesheets/application.css.scss, app/assets/stylesheets/products.scss, app/views/products/_details.html.haml, app/views/products/index.html.haml
商品購入ページの実装を行います。
部分テンプレートでindexに表示させる予定です。
=> 商品詳細ページの実装 [WIP]

Gemfile, Gemfile.lock, app/assets/stylesheets/application.css.scss, app/views/products/index.html.erb
=> 商品購入ページの作成[WIP]

app/assets/stylesheets/_footer.scss, app/assets/stylesheets/_header.scss, app/assets/stylesheets/application.css.scss, app/assets/stylesheets/new_registration.scss, app/controllers/users_controller.rb, app/views/shared/_footer.html.haml, app/views/shared/_header.html.haml, app/views/users/new_registration.html.haml, config/routes.rb
＃ what
- users_controllerを作成
- _footer.html.haml
- _header.html.haml
- new_registration.html.haml
- _footer.scss
- _header.scss
- new_registration.scss を作成
- application.css.scss に、上記の３つのscss を呼び出す記述をした
- new_registrationを呼び出すためにルーティングを追記
- ユーザーの登録周りのコントローラをつくるため
- footer と header は同じページが多く、省略できるため
- コントローラのアクションを呼び出す記載をするため
=> [WIP]新規会員登録の画面を作成

.gitignore, Gemfile, Gemfile.lock, app/uploaders/image_uploader.rb, config/deploy.rb, config/initializers/carrierwave.rb, config/secrets.yaml
#WHAT
S3環境に対する各種設定を記述しました
#WHY
画像アップロードできるようにするためです
=> [WIP]S３環境の構築

app/assets/stylesheets/products/_buy.scss, app/views/products/new.html.haml
商品購入画面のpaddingやmargin，font sizeの調整を行います。
=> 商品購入画面の細かい修正を行います

app/assets/stylesheets/application.css.scss, app/assets/stylesheets/users/_header.registration.scss, app/assets/stylesheets/users/information.scss, app/assets/stylesheets/users/new_registration.scss, app/controllers/users_controller.rb, app/views/shared/_header.registration.html.haml, app/views/users/registrations/information.html.haml
- 会員情報入力画面を作成
- 会員情報入力画面のヘッダーを分けて作成
- それぞれのscssを作成
- コントローラに会員情報入力画面に遷移するような記述を追記
- 必須機能のため
=> [WIP]会員情報入力画面の作成

app/assets/stylesheets/application.css.scss, app/assets/stylesheets/users/login.scss, app/controllers/users_controller.rb, app/views/users/login.html.haml
- ログイン画面のhamlを作成
- ログイン画面のscssを作成
- コントローラを変更
- application.css.scssに追記
- 必須なため
=> [WIP] ログイン画面の作成

app/assets/stylesheets/products/_details-pickup.scss, app/views/products/details.html.haml
=> 商品詳細画面の下部分を実装します

app/controllers/application_controller.rb, config/deploy.rb
#WHAT
Basic認証機能を追加し、サイトに入れる人を制限しました
#WHY
誤ってアクセスしたユーザーに誤解を生むことがないようにするためです
=> [WIP]Basic認証機能の追加

app/assets/stylesheets/application.css.scss, app/assets/stylesheets/users/_payment.scss, app/controllers/users_controller.rb, app/views/shared/registrations/_payment_header.html.haml, app/views/users/registrations/payment.html.haml
- 支払い方法の画面を作成
- ヘッダーを分けて作成
- それに伴いCSSを作成
- コントローラの変更
- 必須なため
=> [WIP]支払い方法の画面作成

app/controllers/application_controller.rb, config/deploy/production.rb
#WHAT
本番環境のみベーシック認証できるように記述を変えました
＃WHY
ローカル環境でベーシック認証がかかるのはだるいからです
=> [WIP]ベーシック認証機能の改善

Gemfile, Gemfile.lock
＃ what
gem 'devise-i18n'
gem 'devise-i18n-views' を追加
devise上で日本語を使うため
=> [WIP]deviseで日本語を使うgemを追加

app/assets/javascripts/details.js, app/views/products/show.html.haml
商品詳細画面にていいね!ボタンを押したら赤く変化するJavaScriptを実装しました。
=> いいねボタンをクリックした時の挙動追加[WIP]

app/controllers/credits_controller.rb, app/controllers/trades_controller.rb
#WHAT
payjpの環境変数を取り出すための記述を修正しました
#WHY
変更する前の記述では環境変数が呼び出せないからです
=> [WIP]環境変数の取り出し記述修正

db/migrate/20190629050535_create_profiles.rb, db/migrate/20190629053930_create_credits.rb, db/migrate/20190629055228_create_products.rb, db/migrate/20190702043518_create_brands.rb, db/migrate/20190702053129_rename_brand_column_to_products.rb, db/migrate/20190702054415_change_datatype_brand_id_of_products.rb, db/migrate/20190702060955_addname_tobrands.rb, db/migrate/20190702064919_addcategories_id_toproducts.rb, db/migrate/20190702081735_remove_product_id_to_categories.rb, db/migrate/20190702085511_add_category_to_product.rb, db/migrate/20190702092356_remove_product_id_to_brands.rb, db/migrate/20190703060039_add_score_to_profile.rb, db/migrate/20190703083155_add_status_to_product.rb, db/migrate/20190704044449_add_customer_id_to_credits.rb, db/migrate/20190704044507_add_card_id_to_credits.rb, db/migrate/20190704044549_remove_number_from_credits.rb, db/migrate/20190704044739_remove_month_from_credits.rb, db/migrate/20190704044803_remove_year_from_credits.rb, db/migrate/20190704044824_remove_security_code_from_credits.rb, db/schema.rb
#WHAT
無駄なmigrationファイルを削除しました
#WHY
migrationファイルが多いためです
=> [WIP]migrationファイルの編集

config/deploy.rb
#WHAT
ベーシック認証の記述を修正しました
#WHY
何回も表示されるのを防ぐためです
=> [WIP]ベーシック認証機能の修正

app/assets/javascripts/user.js, app/assets/stylesheets/users/_address.scss, app/assets/stylesheets/users/_complete.scss, app/assets/stylesheets/users/_information.scss, app/assets/stylesheets/users/_login.scss, app/assets/stylesheets/users/_payment.scss, app/assets/stylesheets/users/_signup.scss, app/controllers/users/registrations_controller.rb, app/views/credits/_new.html.haml, app/views/credits/index.html.haml, app/views/users/registrations/complete.html.haml, app/views/users/registrations/payment.html.haml, config/routes.rb
- debuggerの削除
- fontの修正
- 支払い方法画面の修正
- 支払い方法画面のcreateメソッドを作成
- ルーティングを追加
- クレジットカード登録画面の部分テンプレートを修正
=> ユーザー新規登録の細かい調整

app/assets/javascripts/index_header.js, app/assets/stylesheets/modules/_index_header.scss, app/controllers/products_controller.rb, app/views/products/purchase.html.haml, app/views/shared/_index_header.html.haml
#WHAT 
ログイン後のトップページ上部のヘッダーにアイコンとリストを追加しました
#WHY
見た目をメルカリ本家に近づけるためです
=> [WIP]トップページの編集

README.md, app/assets/javascripts/image_preview.js, app/assets/stylesheets/products/_details.scss, app/controllers/products_controller.rb, app/models/image.rb, app/views/products/_pick_up_brands.html.haml, app/views/products/_pick_up_category.html.haml, app/views/products/new.html.haml, app/views/products/purchase.html.haml, app/views/products/show.html.haml
=> カラム名をurlに変更した際の修正

app/views/products/_pick_up_brands.html.haml, app/views/products/_pick_up_category.html.haml, app/views/products/show.html.haml
本番環境に向けて画像の表示の仕方とトップページからの遷移ができるようにしました。
=> 本番環境に向けて調整

app/assets/stylesheets/products/_buy.scss, app/views/products/purchase.html.haml, app/views/products/show.html.haml, config/routes.rb
#WHAT 
購入画面の商品データをDBから引っ張ってきて表示させるようにしました。
#WHY
出品した商品を購入できるようにするためです。
=> [WIP]商品購入画面の作成

app/assets/javascripts/category.js, app/assets/javascripts/image_preview.js, app/assets/javascripts/sell_page_validates.js, app/assets/stylesheets/products/_new.scss, app/controllers/products_controller.rb, app/models/product.rb, app/views/products/new.html.haml, db/migrate/20190705061209_create_products.rb, db/schema.rb
商品出品時のバリデーション機能実装。
何も入力されていない時にエラーメッセージを出力するようにしました。
全項目入力必須になっているため、空の値が保存されないようにした。
=> 商品出品時のバリデーション機能実装。

app/assets/stylesheets/products/_exhibit.scss, app/controllers/products_controller.rb, app/views/products/exhibit.html.haml, config/routes.rb
#WHAT 
商品出品中のページを作成しました。
#WHY
商品編集機能と商品削除昨日の準備として、作成しました
=> [WIP]出品中ページの作成

app/assets/javascripts/flash.js, app/assets/javascripts/index_header.js, app/assets/stylesheets/modules/flash.scss, app/controllers/trades_controller.rb, app/views/layouts/_notification.html.haml, app/views/layouts/application.html.haml, app/views/products/purchase.html.haml, app/views/trades/index.html.haml, config/routes.rb
#WHAT 
フラッシュメッセージの表示、tarade indexアクションの削除、trade buyアクションのDB連携を記述し、追加しました。
#WHY 
フラッシュメッセージは購入などの確認をわかりやすくするため、
それ以外はコードが冗長にならないようにするためです。
=> [WIP]細かい部分の修正

app/assets/javascripts/image_preview.js, app/assets/stylesheets/mixins/_mixin.scss, app/assets/stylesheets/mypages/selled.scss, app/controllers/mypages_controller.rb, app/controllers/products_controller.rb, app/models/product.rb, app/models/trade.rb, app/views/mypages/_mypage-left.html.haml, app/views/mypages/selled.html.haml, config/routes.rb, db/migrate/20190705061349_create_trades.rb, db/schema.rb
出品中の商品がマイページ画面でステータスの確認ができるようにした。
必須機能のため。
=> [WIP] 出品中のステータス確認画面の実装

app/controllers/credits_controller.rb, app/controllers/trades_controller.rb, db/schema.rb
非ログインユーザーで商品を購入できるようにしました
ログインユーザーでしか商品を購入できなかったためです
=> [WIP]ユーザー1以外でのカード登録

app/controllers/trades_controller.rb, app/views/products/purchase.html.haml
#WHAT 
商品を購入する際にtradeテーブルを更新する機能に変更しました
#WHY 
商品を購入するとtradeテーブルに新しくレコードが作成されるためです
=> [WIP]商品購入機能の修正

app/models/product.rb
What:
トップページのレスポンシブ化させました。
Why:
　マルチメディアに対応させるため
=> [WIP]edit_func_respo_view

app/assets/stylesheets/application.css.scss, app/assets/stylesheets/modules/_index_footer.scss, app/assets/stylesheets/modules/_index_header.scss, app/assets/stylesheets/products/_products.scss, app/assets/stylesheets/slick/_slick-theme.scss, app/assets/stylesheets/slick/_slick.scss, app/controllers/products_controller.rb, app/views/products/_index_category_list.html.haml, app/views/products/_pick_up_brands.html.haml, app/views/products/_pick_up_category.html.haml, app/views/shared/_index_header.html.haml
What : 
トップページのビューをレスポンシブに変更しました。
Why：
　マルチメディア対応をするため
=> [WIP]add_fun_res_top_page

app/assets/javascripts/exhibit.js, app/assets/stylesheets/products/_exhibit.scss, app/controllers/products_controller.rb, app/views/products/exhibit.html.haml
=> 細かい修正を行いました。

app/assets/stylesheets/products/_products.scss, app/views/products/_pick_up_brands.html.haml, app/views/products/_pick_up_category.html.haml
#WHAT 
トップページに表示されている商品で、もし購入されている商品があればSOLDのタグを追加する機能を追加しました。
#WHY 
商品が購入されているかどうかを確認するためです。
=> [WIP]トップページの変更

app/assets/stylesheets/products/_details.scss, app/views/products/show.html.haml
#WHAT 
購入済商品で商品が売り切れになり、購入できない機能を追加しました
#WHY
購入済商品でも商品が購入できたためです。
=> [WIP]購入済商品の購入不可
